
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-14
owner: ucsb-cs156-f25
repo_name: team02-f25-14
pull_requests: [{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-UCSBOrganization-edit-page","number":112,"title":"pn - ucsb organization edit page","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/112"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-editpages","number":111,"title":"Cthrnzhong - editpages","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/111"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-UCSBOrganization-index-page","number":110,"title":"pn - ucsb organization index page","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/110"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-indexpages","number":108,"title":"Cthrnzhong - index pages","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/108"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-create-commit-page","number":107,"title":"Cthrnzhong - create commit page","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/107"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-placeholder-pages","number":91,"title":"Cthrnzhong - placeholder pages","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/91"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrzhong-table","number":90,"title":"Cthrnzhong - recommendation request table","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/90"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-component","number":76,"title":"Cthrnzhong form component for recommendation request ","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/76"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-fixtures","number":68,"title":"cthrnzhong - added fixtures file","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/68"}]
