
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-14
owner: ucsb-cs156-f25
repo_name: team02-f25-14
pull_requests: [{"author":{"id":"U_kgDOCIZ8Xg","is_bot":false,"login":"Fern4ndo99","name":""},"headRefName":"team03-fvelazquez-web","number":130,"title":"Fv - End 2 End Tests for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/130"},{"author":{"id":"U_kgDOCIZ8Xg","is_bot":false,"login":"Fern4ndo99","name":""},"headRefName":"team03-fvelazquez-integration","number":129,"title":"Fv - Added Integration Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/129"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-integrationtest","number":128,"title":"cthrnzhong - added integration test for recommendationrequests","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/128"},{"author":{"id":"U_kgDOCM73Qg","is_bot":false,"login":"KeyiZong27","name":"KEYI ZONG"},"headRefName":"kz-Articles-End2End","number":127,"title":"Kz articles end2 end","url":"https://github.com/ucsb-cs156-f25/team02-f25-14/pull/127"}]
